apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  REACT_APP_USERNAME: "Terekhov"
  REACT_APP_COMPANY_NAME: "itmo"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-l3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-l3
  template:
    metadata:
      labels:
        app: frontend-l3
    spec:
      containers:
        - name: frontend-l3
          image: ifilyaninitmo/itdt-contained-frontend:master
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: config

---

apiVersion: v1
kind: Service
metadata:
  name: np-svc-l3
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
    app: frontend-l3


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-l3
spec:
  tls:
    - secretName: tls-secret
    - hosts:
        - lab3terekhov.com
  rules:
    - host: lab3terekhov.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: np-svc-l3
                port:
                  name: http